[package]
name = "excise"
description = "Surgical terminal storage navigator"
version = "0.0.0-dev"
authors = ["Aram Drevekenin <aram@poor.dev>", "Tom Larcher <tom.larcher@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/findyourexit/excise"
repository = "https://github.com/findyourexit/excise"
license = "MIT"
edition = "2018"
publish = false

[[bin]]
name = "excise"
path = "src/main.rs"

[dependencies]
tui = {version="0.11", default-features = false, features = ['crossterm'] }
crossterm = "0.17"
failure = "0.1"
jwalk = "0.5"
structopt = "0.3"
filesize = "0.2.0"
unicode-width = "0.1.7"
nix = "0.17.0"
[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["securitybaseapi","debugapi"] }

[dev-dependencies]
insta = "0.16.0"
